name: Python Package using Conda

on:
  pull_request: 
    branches:
      -  main
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Test with pytest
      run: |
        echo { toJSON(github }
